reporter: xcode

excluded:
    - RealTrackerSPM/Sources/RealTrackerApp/Generated/*.swift
    - RealTrackerSPM/.build
    - RealTrackerSPM/.swiftpm
    - Utils/.build
    - Utils/.swiftpm
    - Utils/Package.swift

analyzer_rules:
    - unused_import

custom_rules:
    todos_without_ticket_number:
        name: "No TODOs without ticket number"
        regex: "TODO(?!\\([A-Z]+\\-[0-9]+\\))"
        match_kinds:
            - comment
            - comment.mark
            - comment.url
            - doccomment
            - doccomment.field
            - string
        message: "No TODOs are allowed without ticket number, please use format TODO(FD-123) in your strings and comments."
        severity: error
    wip_left_in_source:
        name: "WIP left in source code"
        regex: "WIP"
        match_kinds:
            - comment
            - comment.mark
            - comment.url
            - doccomment
            - doccomment.field
            - string
        message: "WIP is only allowed during development, make sure to remove it before making your PR ready for review."
        severity: warning

disabled_rules:
    - function_parameter_count
    - todo

opt_in_rules:
    - accessibility_label_for_image
    - accessibility_trait_for_button
    - anonymous_argument_in_multiline_closure
    - array_init
    - attributes
    - closure_body_length
    - closure_end_indentation
    - closure_spacing
    - collection_alignment
    - comma_inheritance
    - contains_over_filter_count
    - contains_over_filter_is_empty
    - contains_over_first_not_nil
    - contains_over_range_nil_comparison
    - convenience_type
    - discarded_notification_center_observer
    - discouraged_assert
    - discouraged_object_literal
    - empty_collection_literal
    - empty_count
    - empty_string
    - expiring_todo
    - explicit_init
    - fallthrough
    - fatal_error_message
    - file_name
    - file_name_no_space
    - file_types_order
    - first_where
    - flatmap_over_map_reduce
    - force_unwrapping
    - identical_operands
    - implicitly_unwrapped_optional
    - indentation_width
    - joined_default_parameter
    - last_where
    - legacy_multiple
    - legacy_objc_type
    - let_var_whitespace
    - literal_expression_end_indentation
    - local_doc_comment
    #- missing_docs
    - modifier_order
    - multiline_arguments
    - multiline_arguments_brackets
    - multiline_function_chains
    - multiline_literal_brackets
    - multiline_parameters
    - multiline_parameters_brackets
    - number_separator
    - object_literal
    - operator_usage_whitespace
    - overridden_super_call
    - override_in_extension
    - prefer_self_in_static_references
    - prefer_self_type_over_type_of_self
    - prefer_zero_over_explicit_init
    - prefixed_toplevel_constant
    - private_subject
    #- private_swiftui_state
    - reduce_into
    - redundant_nil_coalescing
    - redundant_self_in_closure
    - redundant_type_annotation
    - return_value_from_void_function
    - sorted_enum_cases
    - sorted_first_last
    - sorted_imports
    - static_operator
    - toggle_bool
    - trailing_closure
    - type_contents_order
    - unavailable_function
    - unhandled_throwing_task
    - unneeded_parentheses_in_closure_argument
    - unowned_variable_capture
    - untyped_error_in_catch
    - vertical_whitespace_between_cases
    - vertical_whitespace_closing_braces
    - vertical_whitespace_opening_braces
    - weak_delegate

accessibility_label_for_image:
    severity: error
accessibility_trait_for_button:
    severity: error
anonymous_argument_in_multiline_closure:
    severity: error
array_init:
    severity: error
attributes:
    severity: error
    always_on_same_line:
        - "@objc"
closure_body_length:
    warning: 50
    error: 60
closure_end_indentation:
    severity: error
closure_spacing:
    severity: error
collection_alignment:
    severity: error
comma_inheritance:
    severity: error
contains_over_filter_count:
    severity: error
contains_over_filter_is_empty:
    severity: error
contains_over_first_not_nil:
    severity: error
contains_over_range_nil_comparison:
    severity: error
convenience_type:
    severity: error
cyclomatic_complexity:
    warning: 16
discarded_notification_center_observer:
    severity: error
discouraged_assert:
    severity: error
discouraged_object_literal:
    severity: error
empty_collection_literal:
    severity: error
empty_count:
    severity: error
empty_string:
    severity: error
explicit_init:
    severity: error
fallthrough:
    severity: error
fatal_error_message:
    severity: error
file_length:
    warning: 600
    error: 1200
file_name:
    severity: error
file_name_no_space:
    severity: error
file_types_order:
    severity: error
first_where:
    severity: error
flatmap_over_map_reduce:
    severity: error
force_unwrapping:
    severity: error
function_body_length:
    warning: 80
identical_operands:
    severity: error
identifier_name:
    allowed_symbols:
        - at
        - id
        - tr
        - vm
    min_length:
        error: 1
        warning: 2
    max_length:
        error: 60
        warning: 50
implicitly_unwrapped_optional:
    severity: error
indentation_width:
    severity: warning
joined_default_parameter:
    severity: error
last_where:
    severity: error
legacy_multiple:
    severity: error
legacy_objc_type:
    severity: error
let_var_whitespace:
    severity: error
line_length:
    warning: 160
    error: 240
literal_expression_end_indentation:
    severity: error
local_doc_comment:
    severity: error
modifier_order:
    severity: error
multiline_arguments:
    severity: error
multiline_arguments_brackets:
    severity: error
multiline_function_chains:
    severity: error
multiline_literal_brackets:
    severity: error
multiline_parameters:
    severity: error
multiline_parameters_brackets:
    severity: error
number_separator:
    severity: error
object_literal:
    severity: error
operator_usage_whitespace:
    severity: error
overridden_super_call:
    severity: error
override_in_extension:
    severity: error
prefer_self_in_static_references:
    severity: error
prefer_self_type_over_type_of_self:
    severity: error
prefer_zero_over_explicit_init:
    severity: error
prefixed_toplevel_constant:
    severity: error
    only_private: true
private_subject:
    severity: error
reduce_into:
    severity: error
redundant_nil_coalescing:
    severity: error
redundant_self_in_closure:
    severity: error
redundant_type_annotation:
    severity: error
return_value_from_void_function:
    severity: error
sorted_enum_cases:
    severity: error
sorted_first_last:
    severity: error
sorted_imports:
    severity: error
static_operator:
    severity: error
toggle_bool:
    severity: error
trailing_closure:
    severity: error
type_contents_order:
    severity: error
type_name:
    max_length:
        error: 60
        warning: 50
unavailable_function:
    severity: error
unhandled_throwing_task:
    severity: error
unneeded_parentheses_in_closure_argument:
    severity: error
unowned_variable_capture:
    severity: error
untyped_error_in_catch:
    severity: error
unused_import:
    severity: error
vertical_whitespace_between_cases:
    severity: error
vertical_whitespace_closing_braces:
    severity: error
vertical_whitespace_opening_braces:
    severity: error
weak_delegate:
    severity: error
